# Generated by Django 4.2.4 on 2023-09-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_tutor_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor_rating",
            old_name="rating",
            new_name="rating_value",
        ),
    ]
