# Generated by Django 4.2.4 on 2023-09-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_rating_tutor_rating_rating_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor_rating",
            name="rating_value",
        ),
    ]
