# Generated by Django 4.2.4 on 2023-09-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_tutor_rating_rating_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor_rating",
            name="rating_value",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tutor_rating",
            name="tut_id",
            field=models.IntegerField(default=0),
        ),
    ]
