# Generated by Django 4.2.4 on 2023-09-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_tutor_rating_rating_value_tutor_rating_tut_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor_rating",
            name="comment",
            field=models.CharField(max_length=500),
        ),
    ]
