# Generated by Django 4.2.4 on 2023-10-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_tutor_rating_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor_rating",
            name="tutor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.private_tutor",
            ),
        ),
    ]
