# Generated by Django 4.2.4 on 2023-10-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_tutor_rating_tutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="tutor_rating",
            name="tutor",
        ),
    ]
