# Generated by Django 4.2.4 on 2023-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_student_remove_tutor_rating_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor_rating",
            name="tut_id",
            field=models.IntegerField(null=True),
        ),
    ]
