# Generated by Django 4.2.4 on 2023-10-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_tutor_rating_tut_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor_rating",
            old_name="tut_id",
            new_name="tut_id1",
        ),
    ]
